In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('rfm_segments.csv')

In [3]:
df.head()

   Customer ID  Recency  Frequency  Monetary  Cluster  Segment
0        12346      326         12  77556.46        1  Regular
1        12347        2          8   5633.32        1  Regular
2        12348       75          5   2019.40        1  Regular
3        12349       19          4   4428.69        1  Regular
4        12350      310          1    334.40        0  At Risk

In [4]:
df['AvgOrderValue'] = df['Monetary'] / df['Frequency']

In [7]:
df.head(10)

   Customer ID  Recency  Frequency  Monetary  Cluster  Segment  AvgOrderValue
0        12346      326         12  77556.46        1  Regular    6463.038333
1        12347        2          8   5633.32        1  Regular     704.165000
2        12348       75          5   2019.40        1  Regular     403.880000
3        12349       19          4   4428.69        1  Regular    1107.172500
4        12350      310          1    334.40        0  At Risk     334.400000
5        12351      375          1    300.93        0  At Risk     300.930000
6        12352       36         10   2849.84        1  Regular     284.984000
7        12353      204          2    406.76        1  Regular     203.380000
8        12354      232          1   1079.40        1  Regular    1079.400000
9        12355      214          2    947.61        1  Regular     473.805000

In [14]:
df.columns.tolist()

['Customer ID',
 'Recency',
 'Frequency',
 'Monetary',
 'Cluster',
 'Segment',
 'AvgOrderValue']

In [15]:
df['Churned'] = (df['Recency'] > 90).astype(int)

In [16]:
df.columns.tolist()

['Customer ID',
 'Recency',
 'Frequency',
 'Monetary',
 'Cluster',
 'Segment',
 'AvgOrderValue',
 'Churned']

In [18]:
df.head(10)

,Customer ID,Recency,Frequency,Monetary,Cluster,Segment,AvgOrderValue,Churned
0,12346,326,12,77556.46,1,Regular,6463.038333,1
1,12347,2,8,5633.32,1,Regular,704.165000,0
2,12348,75,5,2019.40,1,Regular,403.880000,0
3,12349,19,4,4428.69,1,Regular,1107.172500,0
4,12350,310,1,334.40,0,At Risk,334.400000,1
5,12351,375,1,300.93,0,At Risk,300.930000,1
6,12352,36,10,2849.84,1,Regular,284.984000,0
7,12353,204,2,406.76,1,Regular,203.380000,1
8,12354,232,1,1079.40,1,Regular,1079.400000,1
9,12355,214,2,947.61,1,Regular,473.805000,1

In [19]:
df.to_csv('rfm_features_full.csv', index=False)

In [20]:
churn_rate = df['Churned'].mean()

In [22]:
print(churn_rate)

0.508506294658047

In [27]:
df.head()

,Customer ID,Recency,Frequency,Monetary,Cluster,Segment,AvgOrderValue,Churned,CLV
0,12346,326,12,77556.46,1,Regular,6463.038333,1,152518.190659
1,12347,2,8,5633.32,1,Regular,704.165000,0,11078.171616
2,12348,75,5,2019.40,1,Regular,403.880000,0,3971.238943
3,12349,19,4,4428.69,1,Regular,1107.172500,0,8709.213724
4,12350,310,1,334.40,0,At Risk,334.400000,1,657.612312

In [23]:
estimated_lifespan_months = 1 / churn_rate

In [25]:
print(estimated_lifespan_months)

1.966543994647039

In [28]:
df['CLV'] = df['AvgOrderValue'] * df['Frequency'] * estimated_lifespan_months
df[['Customer ID', 'AvgOrderValue', 'Frequency', 'CLV']].sort_values('CLV', ascending=False).head(10)

      Customer ID  AvgOrderValue  Frequency           CLV
5692        18102    4198.770000        145  1.197275e+06
2277        14646    3500.678940        151  1.039520e+06
1789        14156    2012.476731        156  6.173893e+05
2538        14911     743.649824        398  5.820432e+05
5050        17450    4842.609608         51  4.856834e+05
1331        13694    1374.005664        143  3.863921e+05
5109        17511    2926.725833         60  3.453321e+05
4061        16446   84236.250000          2  3.313086e+05
4295        16684    2675.323091         55  2.893627e+05
68          12415    5159.227500         28  2.840837e+05

In [29]:
df.to_csv('clv_results.csv', index=False)

In [31]:
df.head()

,Customer ID,Recency,Frequency,Monetary,Cluster,Segment,AvgOrderValue,Churned,CLV
0,12346,326,12,77556.46,1,Regular,6463.038333,1,152518.190659
1,12347,2,8,5633.32,1,Regular,704.165000,0,11078.171616
2,12348,75,5,2019.40,1,Regular,403.880000,0,3971.238943
3,12349,19,4,4428.69,1,Regular,1107.172500,0,8709.213724
4,12350,310,1,334.40,0,At Risk,334.400000,1,657.612312

In [30]:
df.shape

(5878, 9)