In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [8]:
df = pd.read_csv('online_retail_sales_cleaned.csv')
df['InvoiceDate'] = pd.to_datetime(df['InvoiceDate'])

In [20]:
df.shape

(805549, 9)

In [9]:
df.head(10)

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country,TotalPrice
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085,United Kingdom,83.4
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085,United Kingdom,81.0
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085,United Kingdom,81.0
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085,United Kingdom,100.8
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085,United Kingdom,30.0
5,489434,22064,PINK DOUGHNUT TRINKET POT,24,2009-12-01 07:45:00,1.65,13085,United Kingdom,39.6
6,489434,21871,SAVE THE PLANET MUG,24,2009-12-01 07:45:00,1.25,13085,United Kingdom,30.0
7,489434,21523,FANCY FONT HOME SWEET HOME DOORMAT,10,2009-12-01 07:45:00,5.95,13085,United Kingdom,59.5
8,489435,22350,CAT BOWL,12,2009-12-01 07:46:00,2.55,13085,United Kingdom,30.6
9,489435,22349,"DOG BOWL , CHASING BALL DESIGN",12,2009-12-01 07:46:00,3.75,13085,United Kingdom,45.0

In [10]:
popular_products = df.groupby('Description')['Quantity'].sum().sort_values(ascending=False)

In [12]:
top_10_popular = popular_products.head(10)

In [15]:
top_10_popular.head(10)

Description
WORLD WAR 2 GLIDERS ASSTD DESIGNS     109169
WHITE HANGING HEART T-LIGHT HOLDER     93640
PAPER CRAFT , LITTLE BIRDIE            80995
ASSORTED COLOUR BIRD ORNAMENT          79913
MEDIUM CERAMIC TOP STORAGE JAR         77916
JUMBO BAG RED RETROSPOT                75759
BROCADE RING PURSE                     71129
PACK OF 60 PINK PAISLEY CAKE CASES     55270
60 TEATIME FAIRY CAKE CASES            53495
PACK OF 72 RETROSPOT CAKE CASES        46107
Name: Quantity, dtype: int64

In [17]:
top_100_products = df.groupby('Description')['Quantity'].sum().sort_values(ascending=False).head(100).index
df_sample = df[df['Description'].isin(top_100_products)]

In [23]:
top_100_products

Index(['WORLD WAR 2 GLIDERS ASSTD DESIGNS',
       'WHITE HANGING HEART T-LIGHT HOLDER', 'PAPER CRAFT , LITTLE BIRDIE',
       'ASSORTED COLOUR BIRD ORNAMENT', 'MEDIUM CERAMIC TOP STORAGE JAR',
       'JUMBO BAG RED RETROSPOT', 'BROCADE RING PURSE ',
       'PACK OF 60 PINK PAISLEY CAKE CASES', '60 TEATIME FAIRY CAKE CASES',
       'PACK OF 72 RETROSPOT CAKE CASES', 'PACK OF 72 RETRO SPOT CAKE CASES',
       'SMALL POPCORN HOLDER', 'MINI PAINT SET VINTAGE ',
       'ASSORTED COLOURS SILK FAN', 'COLOUR GLASS T-LIGHT HOLDER HANGING',
       'PACK OF 72 SKULL CAKE CASES', 'PACK OF 12 LONDON TISSUES ',
       'VICTORIAN GLASS HANGING T-LIGHT', 'RED  HARMONICA IN BOX ',
       'JUMBO BAG STRAWBERRY', 'STRAWBERRY CERAMIC TRINKET BOX',
       'GIRLS ALPHABET IRON ON PATCHES ', '72 SWEETHEART FAIRY CAKE CASES',
       'PACK OF 12 SUKI TISSUES ', 'PACK OF 60 DINOSAUR CAKE CASES',
       'POPCORN HOLDER', 'SMALL CHINESE STYLE SCISSOR',
       'HANGING JAM JAR T-LIGHT HOLDER', 'ROTATING SILVER ANGELS T-LIGHT HLDR',
       'PAPER CHAIN KIT 50'S CHRISTMAS ', 'JUMBO  BAG BAROQUE BLACK WHITE',
       'RED TOADSTOOL LED NIGHT LIGHT', 'PLACE SETTING WHITE HEART',
       'RABBIT NIGHT LIGHT', 'HEART OF WICKER SMALL', 'JUMBO STORAGE BAG SUKI',
       'PACK OF 12 WOODLAND TISSUES ', 'LUNCH BAG  BLACK SKULL.',
       '60 CAKE CASES VINTAGE CHRISTMAS', 'HANGING HEART ZINC T-LIGHT HOLDER',
       'VINTAGE SNAP CARDS', 'BLACK AND WHITE PAISLEY FLOWER MUG',
       'PACK OF 12 PINK PAISLEY TISSUES ', 'PACK OF 12 HEARTS DESIGN TISSUES ',
       'REGENCY CAKESTAND 3 TIER', 'JUMBO SHOPPER VINTAGE RED PAISLEY',
       'ASSORTED FLOWER COLOUR "LEIS"', 'JUMBO BAG PINK VINTAGE PAISLEY',
       'JUMBO BAG PINK POLKADOT', 'PARTY BUNTING', 'LUNCH BAG CARS BLUE',
       'PLEASE ONE PERSON METAL SIGN', 'PACK OF 12 RED SPOTTY TISSUES ',
       'ASSTD DESIGN BUBBLE GUM RING', 'MULTI COLOUR SILVER T-LIGHT HOLDER',
       'DISCO BALL CHRISTMAS DECORATION', 'LUNCH BAG WOODLAND',
       'PACK OF 60 SPACEBOY CAKE CASES', 'PINK BLUE FELT CRAFT TRINKET BOX',
       'LUNCH BAG RED RETROSPOT', 'SPACEBOY LUNCH BOX ',
       'PINK CREAM FELT CRAFT TRINKET BOX ', 'GIN + TONIC DIET METAL SIGN',
       'COOK WITH WINE METAL SIGN ', 'JUMBO BAG OWLS', 'GRAND CHOCOLATECANDLE',
       'ZINC METAL HEART DECORATION', 'BLACK RECORD COVER FRAME',
       'ANTIQUE SILVER TEA GLASS ETCHED', 'WOODLAND CHARLOTTE BAG',
       'HANGING HEART JAR T-LIGHT HOLDER', 'LUNCH BAG SPACEBOY DESIGN ',
       'SWEETHEART CERAMIC TRINKET BOX', 'SET/6 RED SPOTTY PAPER PLATES',
       'BOYS ALPHABET IRON ON PATCHES', 'CREAM HEART CARD HOLDER',
       'HEART OF WICKER LARGE', 'RED HANGING HEART T-LIGHT HOLDER',
       'BOX OF 24 COCKTAIL PARASOLS', 'DOLLY GIRL LUNCH BOX',
       'AGED GLASS SILVER T-LIGHT HOLDER', 'FANCY FONTS BIRTHDAY WRAP',
       'PACK OF 6 BIRDY GIFT TAGS', 'LUNCH BAG RED SPOTTY',
       'PAPER CHAIN KIT VINTAGE CHRISTMAS',
       'GROW A FLYTRAP OR SUNFLOWER IN TIN', 'PACK OF 12 TRADITIONAL CRAYONS',
       'VINTAGE HEADS AND TAILS CARD GAME ', 'BAG 250g SWIRLY MARBLES',
       'HEART FILIGREE DOVE  SMALL', 'WRAP PINK FAIRY CAKES ',
       'SINGLE HEART ZINC T-LIGHT HOLDER', 'JAM MAKING SET PRINTED',
       'JUMBO BAG SPACEBOY DESIGN', 'SET/6 FRUIT SALAD PAPER CUPS',
       'SPACEBOY BIRTHDAY CARD', 'HAND OVER THE CHOCOLATE   SIGN ',
       '6 RIBBONS RUSTIC CHARM', 'SET/6 RED SPOTTY PAPER CUPS',
       'LUNCH BOX I LOVE LONDON'],
      dtype='object', name='Description')

In [18]:
df_sample.shape

(110649, 9)

In [24]:
customer_product_matrix = df_sample.pivot_table(
    index='Customer ID',
    columns='Description',
    values='Quantity',
    aggfunc='sum',
    fill_value=0
)

In [25]:
customer_product_matrix.shape

(5194, 100)

In [26]:
customer_product_matrix.head()

Description,6 RIBBONS RUSTIC CHARM,60 CAKE CASES VINTAGE CHRISTMAS,60 TEATIME FAIRY CAKE CASES,72 SWEETHEART FAIRY CAKE CASES,AGED GLASS SILVER T-LIGHT HOLDER,ANTIQUE SILVER TEA GLASS ETCHED,ASSORTED COLOUR BIRD ORNAMENT,ASSORTED COLOURS SILK FAN,"ASSORTED FLOWER COLOUR ""LEIS""",ASSTD DESIGN BUBBLE GUM RING,...,STRAWBERRY CERAMIC TRINKET BOX,SWEETHEART CERAMIC TRINKET BOX,VICTORIAN GLASS HANGING T-LIGHT,VINTAGE HEADS AND TAILS CARD GAME,VINTAGE SNAP CARDS,WHITE HANGING HEART T-LIGHT HOLDER,WOODLAND CHARLOTTE BAG,WORLD WAR 2 GLIDERS ASSTD DESIGNS,WRAP PINK FAIRY CAKES,ZINC METAL HEART DECORATION
Customer ID,,,,,,,,,,,,,,,,,,,,,
12346,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
12347,0,0,96,96,0,0,0,0,0,0,...,0,0,0,48,0,0,50,0,0,0
12348,0,144,168,96,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
12349,0,0,0,0,0,0,16,0,0,0,...,48,84,0,0,0,0,0,0,50,0
12350,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [27]:
from sklearn.metrics.pairwise import cosine_similarity

In [28]:
product_similarity = cosine_similarity(customer_product_matrix.T)

In [32]:
product_similarity.shape

(100, 100)

In [33]:
product_similarity_df = pd.DataFrame(
    product_similarity,
    index=customer_product_matrix.columns,
    columns=customer_product_matrix.columns
)

In [34]:
product_similarity_df.shape

(100, 100)

In [35]:
product_similarity_df.head()

Description,6 RIBBONS RUSTIC CHARM,60 CAKE CASES VINTAGE CHRISTMAS,60 TEATIME FAIRY CAKE CASES,72 SWEETHEART FAIRY CAKE CASES,AGED GLASS SILVER T-LIGHT HOLDER,ANTIQUE SILVER TEA GLASS ETCHED,ASSORTED COLOUR BIRD ORNAMENT,ASSORTED COLOURS SILK FAN,"ASSORTED FLOWER COLOUR ""LEIS""",ASSTD DESIGN BUBBLE GUM RING,...,STRAWBERRY CERAMIC TRINKET BOX,SWEETHEART CERAMIC TRINKET BOX,VICTORIAN GLASS HANGING T-LIGHT,VINTAGE HEADS AND TAILS CARD GAME,VINTAGE SNAP CARDS,WHITE HANGING HEART T-LIGHT HOLDER,WOODLAND CHARLOTTE BAG,WORLD WAR 2 GLIDERS ASSTD DESIGNS,WRAP PINK FAIRY CAKES,ZINC METAL HEART DECORATION
Description,,,,,,,,,,,,,,,,,,,,,
6 RIBBONS RUSTIC CHARM,1.000000,0.249821,0.178522,0.139775,0.023111,0.054951,0.156145,0.145676,0.055434,0.028522,...,0.098440,0.042488,0.087229,0.069645,0.083615,0.334220,0.571803,0.032741,0.159715,0.536958
60 CAKE CASES VINTAGE CHRISTMAS,0.249821,1.000000,0.262974,0.225422,0.006241,0.201539,0.124588,0.072906,0.035323,0.066398,...,0.071597,0.054201,0.040048,0.103708,0.217578,0.164194,0.217893,0.075158,0.224572,0.160447
60 TEATIME FAIRY CAKE CASES,0.178522,0.262974,1.000000,0.931286,0.013180,0.018560,0.039615,0.045878,0.120703,0.051487,...,0.128688,0.139281,0.015854,0.085258,0.186305,0.137504,0.177371,0.044250,0.020981,0.166144
72 SWEETHEART FAIRY CAKE CASES,0.139775,0.225422,0.931286,1.000000,0.013973,0.014312,0.030168,0.028299,0.105140,0.045883,...,0.080936,0.073073,0.016110,0.060858,0.143457,0.108910,0.169509,0.019448,0.012488,0.157963
AGED GLASS SILVER T-LIGHT HOLDER,0.023111,0.006241,0.013180,0.013973,1.000000,0.133482,0.017827,0.006399,0.009463,0.021631,...,0.020577,0.005830,0.104366,0.005600,0.015828,0.029015,0.005852,0.004981,0.004849,0.023550

In [37]:
def get_similar_products(product_name, top_n=10):
    similar_scores = product_similarity_df[product_name].sort_values(ascending=False)
    similar_scores = similar_scores.drop(product_name)
    return similar_scores.head(top_n)

In [38]:
get_similar_products('WHITE HANGING HEART T-LIGHT HOLDER')

Description
RED HANGING HEART T-LIGHT HOLDER    0.564282
GIN + TONIC DIET METAL SIGN         0.503930
HEART OF WICKER SMALL               0.488864
HEART OF WICKER LARGE               0.469306
LUNCH BAG RED RETROSPOT             0.412766
LUNCH BAG SPACEBOY DESIGN           0.392606
SPACEBOY BIRTHDAY CARD              0.388951
VICTORIAN GLASS HANGING T-LIGHT     0.388208
HEART FILIGREE DOVE  SMALL          0.386347
PLEASE ONE PERSON METAL SIGN        0.382830
Name: WHITE HANGING HEART T-LIGHT HOLDER, dtype: float64

In [39]:
product_similarity_df.to_csv('product_similarity_matrix.csv')

In [40]:
product_similarity_df.shape

(100, 100)